/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operacionespolinomios;

/**
 *
 * @author Carolina
 */
public class OperaPolinomios extends javax.swing.JFrame {

    /**
     * Creates new form OperaPolinomios
     */
    public OperaPolinomios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PolinomioA = new javax.swing.JTextField();
        PolinomioB = new javax.swing.JTextField();
        Sumar = new javax.swing.JButton();
        MultiplicarCoef = new javax.swing.JButton();
        MutiplicarPolinomios = new javax.swing.JButton();
        Derivar = new javax.swing.JButton();
        IngresarA = new javax.swing.JButton();
        IngresarB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese Polinomios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Resultado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        PolinomioA.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        PolinomioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolinomioAActionPerformed(evt);
            }
        });
        getContentPane().add(PolinomioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, 170, 30));

        PolinomioB.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        PolinomioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolinomioBActionPerformed(evt);
            }
        });
        getContentPane().add(PolinomioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 91, 170, 30));

        Sumar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Sumar.setText("Sumar dos polinomios");
        Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarActionPerformed(evt);
            }
        });
        getContentPane().add(Sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        MultiplicarCoef.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        MultiplicarCoef.setText("Multiplicar por coeficiente");
        getContentPane().add(MultiplicarCoef, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, -1));

        MutiplicarPolinomios.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        MutiplicarPolinomios.setText("Multiplicar dos polinomios");
        getContentPane().add(MutiplicarPolinomios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        Derivar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Derivar.setText("Derivar polinomio");
        getContentPane().add(Derivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, -1));

        IngresarA.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        IngresarA.setText("Ingresar");
        IngresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        IngresarB.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        IngresarB.setText("Ingresar");
        IngresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 90, -1));

        Resultado.setColumns(20);
        Resultado.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 240, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PolinomioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolinomioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PolinomioAActionPerformed

    private void PolinomioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolinomioBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PolinomioBActionPerformed

    private void IngresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarAActionPerformed

    private void IngresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarBActionPerformed

    private void SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperaPolinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperaPolinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperaPolinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperaPolinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperaPolinomios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Derivar;
    private javax.swing.JButton IngresarA;
    private javax.swing.JButton IngresarB;
    private javax.swing.JButton MultiplicarCoef;
    private javax.swing.JButton MutiplicarPolinomios;
    private javax.swing.JTextField PolinomioA;
    private javax.swing.JTextField PolinomioB;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton Sumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
